### ISSUE TITLE
[Feature] Integrate TorD's Plugin Framework

### ISSUE THREAD

**Issue by K3nny567** [K3nny567/Cheat-Menu-Framework#16]
# Upcoming Feature:

### Benefits
Allows better load-order customization.

### To-do:
- [x] Integrate the Plugin Framework.
- [x] Store the load-order in loadorder.json instead of in the plugin setup script.
- [x] Change the Plugins.package function to load the scripts normally instead of merging them into scripts.rb, as script combining won't be needed due to mod scripts not being compressed when the game is in WRITINGLIST mode.
- Add ingame load-order changing (to apply on next game launch) - removed checkbox as this will be left for a later date
